# Generated by Django 5.2.1 on 2025-09-12 00:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0006_alter_transaction_is_approved2'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='is_approved2',
            field=models.BooleanField(default=False),
        ),
    ]
