# Generated by Django 5.2.1 on 2025-06-06 18:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_product_damaged_quantity_product_purchased_quantity_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='total_quantity',
            new_name='quantity',
        ),
    ]
