# Generated by Django 5.2.1 on 2025-07-28 14:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_rename_qr_code_product_barcode'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='barcode',
            new_name='qr_code',
        ),
    ]
