# Generated by Django 5.2.1 on 2025-06-06 18:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ProductStatus',
        ),
    ]
