# Generated by Django 5.2.1 on 2025-09-11 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0004_userbalance'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='is_approved2',
            field=models.BooleanField(default=False),
        ),
    ]
