# Generated by Django 5.2.1 on 2025-07-28 14:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_product_qr_code'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='qr_code',
            new_name='barcode',
        ),
    ]
